---
kind: Service
apiVersion: v1
metadata:
  name: freakachooup-learndocker-service
spec:
  selector:
    app: freakachooup-learndocker
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8081
      # Port to forward to inside the pod
      targetPort: 4000
      # Port accessible outside cluster
      nodePort: 30004
      name: "tcp-test-port"
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: freakachooup-learndocker-deployment
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: freakachooup-learndocker
    spec:
      containers:
        - name: freakachooup-learndocker-container
          image: freakachooup/learndocker
          ports:
            - containerPort: 4000
