---
kind: Service
apiVersion: v1
metadata:
  name: freakachooup-learning-k8s-service
spec:
  selector:
    app: freakachooup-learning-k8s
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8081
      # Port to forward to inside the pod
      targetPort: 4000
      # Port accessible outside cluster
      nodePort: 30004
      name: "tcp-test-port"
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: freakachooup-learning-k8s-deployment
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2        # how many pods we can add at a time
      maxUnavailable: 0  # maxUnavailable define how many pods can be unavailable
                         # during the rolling update
  template:
    metadata:
      labels:
        app: freakachooup-learning-k8s
    spec:
      containers:
        - name: freakachooup-learning-k8s-container
          image: freakachooup/learning-k8s:latest
          ports:
            - containerPort: 4000
          imagePullPolicy: Always
